using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;

namespace DataAccess.Common
{
    public class cls_HelpMethods
    {
        private ApplicationContext _context;
        //public static string CompanyID { get; set; }
        //public static string CompanyBranchID { get; set; }
        //public static string Company { get; set; }
        //public static string CompanyBranch { get; set; }
        //public static string UserID { get; set; }
        //public static string UserName { get; set; }

        public void UserDetail()
        {
            try
            {
                //using (db)
                {
                    var user = "";// HttpContext.Current.User.Identity.Name;
                    if (user != null && user != "")
                    {
                        //var userID = db.Users.FirstOrDefault(p => p.UserName == user).Id;

                        //var company = db.tbl_securityUserMaster.FirstOrDefault(p => p.userLoged_ID == userID);
                        //if (company != null)
                        //{
                        //    System.Web.HttpContext.Current.Session["user_ID"] = company.user_ID.ToString();
                        //    System.Web.HttpContext.Current.Session["userName"] = company.userName.ToString();

                        //    var userIdentity = (ClaimsIdentity)HttpContext.Current.User.Identity;
                        //    var claims = userIdentity.Claims;
                        //    var roleClaimType = userIdentity.RoleClaimType;
                        //    var roles = claims.Where(c => c.Type == roleClaimType).ToList();

                        //    string sRoles = "";
                        //    List<string> lstRoles = new List<string>();
                        //    foreach (var item in roles)
                        //    {
                        //        lstRoles.Add(item.Value);
                        //    }
                        //    sRoles = String.Join(", ", lstRoles);
                        //    System.Web.HttpContext.Current.Session["userGroup"] = sRoles;
                        //}
                    }
                }
            }
            catch (Exception)
            {
            }
        }

        public void CompanyDetail()
        {
            try
            {
                //using (db)
                {
                    //var company = db.tbl_genCompanyInfo.FirstOrDefault();
                    //if (company != null)
                    {
                        //System.Web.HttpContext.Current.Session["company_ID"] = company.company_ID.ToString();
                        //System.Web.HttpContext.Current.Session["companyName"] = company.companyName.ToString();

                        //var branch = db.tbl_genCompanyBranchMaster.Where(p => p.company_ID == company.company_ID).FirstOrDefault();
                        //if (branch != null)
                        //{
                        //    System.Web.HttpContext.Current.Session["companyBranch_ID"] = branch.companyBranch_ID.ToString();
                        //    System.Web.HttpContext.Current.Session["branchName"] = branch.branchName.ToString();
                        //}
                    }
                }
            }
            catch (Exception)
            {
            }

        }

        //public static DataSet ExecQuery(string sQuery)
        //{
        //    //string cnnString = System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        //    //SqlConnection Sqlcon = new SqlConnection(cnnString);
        //    //SqlDataAdapter Sqlda;
        //    //DataSet ds = new DataSet();

        //    //Sqlcon.Open();
        //    //Sqlda = new SqlDataAdapter(sQuery, Sqlcon);
        //    //Sqlda.Fill(ds);
        //    //Sqlcon.Close();
        //    //return (ds);
        //}

    }

    public class cls_AutoCode
    {
        private ApplicationContext _context;
        public static bool isAutoGenerate { get; set; }
        public static int iRecordCount { get; set; }

        public int Autogenerated_Form(int id)
        {
            int iReturnCount = 0;
            if (id > 0)
            {
                var function = _context.tbl_securityFunctionMaster.Find(id.ToString());
                if (function != null)
                {
                    int iCount = iReturnCount = function.counter;
                    function.counter = ++iCount;
                    _context.Entry(function).State = EntityState.Modified;
                    _context.SaveChanges();
                }
            }
            return iReturnCount;
        }

        public bool isAutogenerated_Form(int iFormID)
        {
            bool bStatus = false;
            if (iFormID > 0)
            {
                bStatus = _context.tbl_securityFunctionMaster.Find(iFormID.ToString()).isAutoGenerate ? true : false;
                isAutoGenerate = bStatus;
            }
            return bStatus;
        }

        public static string AutoCode(int iFormID)
        {
            string sValue = "";
            cls_AutoCode oAutoCode = new cls_AutoCode();
            if (oAutoCode.isAutogenerated_Form(iFormID))
                sValue = oAutoCode.Autogenerated_Form(iFormID).ToString();

            return sValue;
        }
    }

}
